version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.7.2-management
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "myUser"
      RABBITMQ_DEFAULT_PASS: "myPass"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
       - .\data\rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672"